package com.SatyaBhushan.controllers;

import com.SatyaBhushan.dtos.Bill.GenerateBillRequestDto;
import com.SatyaBhushan.dtos.Bill.GenerateBillResponseDto;
import com.SatyaBhushan.dtos.Ticket.ResponseStatus;
import com.SatyaBhushan.models.Bill;
import com.SatyaBhushan.services.BillService;

public class BillController {
//    CreateBill
    private BillService billService ;
    public BillController(BillService billService){
        this.billService = billService ;
    }
    /*
    private Date exitTime ; -- Can be generated by us
    private Ticket ticket ; -- TicketID
    private Operator issuedByOperator ; -- Based on Exitgate we can get this
    private int amount ; -- Should be obtained by TimeDifference from ticket + mapped amount perhr
    private Gate exitGate ;
     */
    public GenerateBillResponseDto createBill(GenerateBillRequestDto requestDto){
        Long ticketId = requestDto.getTicketId();
        Long gateId = requestDto.getExitGateId();
        Bill bill = billService.createBill(ticketId , gateId);
        GenerateBillResponseDto responseDto = new GenerateBillResponseDto();
        responseDto.setAmount(bill.getAmount());
        responseDto.setOperationName(bill.getExitGate().getCurrentOperator().getName());
        responseDto.setPaymentLink("http://paymentLink.com"+bill.getId()+"/pay");
        responseDto.setResponseStatus(ResponseStatus.SUCCESS);
        responseDto.setMessage("Bill Generated Successfully");
        return responseDto ;
    }

}

